<?php
/**
 * @file
 * Code for the COD BoF Session feature.
 */

include_once('cod_bof.features.inc');

function cod_bof_views_pre_view(&$view, &$display_id, &$args) {

  if($view->name == 'sessions' && $display_id == 'block_3' && $args[1] == 'bof_session') {
    $footer = cod_bof_get_bof_link($args[0]);
    $options = array(
      'id' => 'area',
      'table' => 'views',
      'field' => 'area',
      'empty' => $footer['display'],
      'content' => $footer['content'],
      'format' => 'full_html',
      'tokenize' => 0,
    );
    $view->set_item('block_3', 'footer', 'area', $options);
  }
}

function cod_bof_get_bof_link($time_slot_entity) {
  //dpm($room_nid . ' and ' . $time_nid);
  $field_collection_item = field_collection_item_load($time_slot_entity); // Load that field collection item.

  $footer['display'] = FALSE;
  $footer['content'] = '';

  /* find out if there are any sessions currently assigned to a room at a given time */
  $result = db_select('field_data_field_session_timeslot', 'f')
    ->fields('f', array('field_session_timeslot_target_id'))
    ->condition('field_session_timeslot_target_id', $time_slot_entity)
    ->execute();
  $bof_count = $result->rowCount();

  $bof_allowed = FALSE;
  foreach($field_collection_item->field_slot_types_allowed[LANGUAGE_NONE] AS $slot_types) {
    if($slot_types['value'] == 'bof_session') {
      $bof_allowed = TRUE;
    }
  }
  if(!empty($field_collection_item->field_slot_types_capacity)) {
    if($bof_allowed && $bof_count < $field_collection_item->field_slot_types_capacity[LANGUAGE_NONE][0]['value']) {
      if(user_access('create bof_session content')) {
        $footer['content'] = l('Create a BoF','node/add/bof-session',array('query' => array('edit[field_session_timeslot][target_id]' => $time_slot_entity, 'destination' => 'program/schedule/bofs')));
        $footer['display'] = TRUE;
      }
    }
  }
  return $footer;
}